name: local_storage_cofeeholic_api
description: Implementation of the CofeeholicApi that uses local storage.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.3

dependencies:
  cofeeholic_api:
    path: ../cofeeholic_api
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.5
  meta: ^1.7.0
  path:
  rxdart: ^0.27.5
  shared_preferences: ^2.0.15

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  very_good_analysis: ^3.1.0
