// This file is "main.dart"
import 'package:cofeeholic_api/cofeeholic_api.dart';
import 'package:flutter/foundation.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'discover_state.freezed.dart';

@freezed
class DiscoverState with _$DiscoverState {
  const factory DiscoverState({
    @Default(DiscoverStatus.initial) DiscoverStatus status,
    CoffeeImage? currentImage,
    CoffeeImage? discardedImage,
  }) = _DiscoverState;
}

enum DiscoverStatus { initial, loading, success, failure }
