// This file is "main.dart"
import 'package:cofeeholic_api/cofeeholic_api.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'favorites_state.freezed.dart';

@freezed
class FavoriteState with _$FavoriteState {
  const factory FavoriteState({
    @Default(FavoritesStatus.initial) FavoritesStatus status,
    @Default(<CoffeeImage>[]) List<CoffeeImage> images,
  }) = _FavoriteState;
}

enum FavoritesStatus { initial, loading, success, failure }
